apiVersion: apps/v1
kind: Deployment
metadata:
  name: booked-deployment
spec:
  selector:
    matchLabels:
      app: booked
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: booked
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
