apiVersion: apps/v1
kind: Deployment
metadata:
  name: booked
  labels:
    app: booked
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booked
  template:
    metadata:
      name: booked
      labels:
        app: booked
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: worker
      containers:
      - name: booked
        image: cmott97/booked:latest
